AllCops:
  TargetRubyVersion: 2.4

Metrics/AbcSize:
  Max: 25

Metrics/LineLength:
  Max: 120

Metrics/ClassLength:
  Max: 120

Metrics/MethodLength:
  Max: 15

Metrics/CyclomaticComplexity:
  Max: 10

Style/FrozenStringLiteralComment:
  Enabled: false
